### ISSUE TITLE
The response of the API changed

### ISSUE THREAD

**Issue by nilsreichardt** [paulbrejla/ferien-api#19]
A few days ago, the behavior of the API changed.

Previous, the response was something like this:

```json
[
    {
        "start": "2022-01-31",
        "end": "2022-02-01",
        "year": 2022,
        "stateCode": "HB",
        "name": "winterferien",
        "slug": "winterferien-2022-HB"
    }
]
```

Now it changed to:

```json
[
    {
        "start": "2022-01-31",
        "end": "2022-02-01",
        "year": 2022,
        "stateCode": "HB",
        "name": "winterferien bremen 2022",
        "slug": "winterferien bremen 2022-2022-HB"
    }
]
```

Especially the name of the holiday changed which broke our app:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/24459435/193341235-75037f2f-e49b-4e14-82b5-c3b07d7a0765.png">

(Normally "nordrhein-westfalen" shouldn't be there)

**Comment by paulbrejla** [comment]
Hi,

this occurred due to changing the data source to pull ics files from a separate repo. These files were re-created so some things may have changed along the way.

To recap:
- If you need data changes etc, feel free to contribute a pr to this repo or the linked ferien-api-data repo.
- If your app really really depends on this for production, I recommend to run the application yourself (it is quite simple) as I do not have the time to ensure compatibility with existing consumers.

Hope this helps.

Cheers
Paul
